micronaut:
  application:
    name: demo
#  data:
#    mongodb:
#      create-collections: true
#mongodb:
#  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
#test-resources:
#  containers:
#    mongodb:
#      image-name: mongodb:latest
#      db-name: testdb
netty:
  default:
    allocator:
      max-order: 3
