site_name: Micronaut by Example

repo_url: https://github.com/hantsy/micronaut-sandbox
repo_name: hantsy/micronaut-sandbox
theme:
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  features:
    - search.suggest
    - navigation.expand
    - navigation.indexes
    # - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt 

copyright: Copyright &copy;2022 Hantsy  
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hantsy  
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hantsy  
    - icon: fontawesome/brands/medium
      link: https://medium.com/@hantsy   
    - icon: fontawesome/brands/github
      link: https://github.com/hantsy   

markdown_extensions:
  - meta
  - toc:
      toc_depth: 3
      permalink: true      
plugins:
  - search
  - git-revision-date    
  
nav:
  - Introduction to Micronaut:
    - index.md
  - Getting Started:
    - gs/index.md
    - Prerequisites: gs/prerequisites.md
    - Generating Project Skeleton: gs/gen.md 
    - Building & Running Application: gs/build.md
    - "Example: Java + Micronaut Data JPA": gs/gs-rest.md   
    - "Example: Kotlin + Micronaut Data JDBC": gs/jdbc-kotlin.md
    - "Example: Kotlin Coroutine + Micronaut Data R2DBC": gs/r2dbc-kotlin-co.md    
    - "Example: Java + Micronaut Mongo Reactive": gs/mongo-reactive.md      