micronaut:
  application:
    name: demo
jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        connection:
#          url: jdbc:postgresql://localhost:5432/blogdb
#          username: user
#          password: password
          db-type: postgres

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false

netty:
  default:
    allocator:
      max-order: 3
