micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/blogdb
    driverClassName: org.postgresql.Driver
    username: user
    password: password
    #schema-generate: CREATE_DROP
    schema-generate: NONE
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false