micronaut:
  application:
    name: demo
datasources:
  default:
#    url: jdbc:postgresql://localhost:5432/blogdb
#    username: user
#    password: password
    #schema-generate: CREATE_DROP
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      baselineOnMigrate: true
      baseline-version: 0

netty:
  default:
    allocator:
      max-order: 3
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false
