micronaut:
  application:
    name: demo
  server:
    port: 8080
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/blogdb
    driverClassName: org.postgresql.Driver
    username: user
    password: password
    schema-generate: NONE
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/blogdb
      username: user
      password: password

netty:
  default:
    allocator:
      max-order: 3

