# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: post-service

on:
  push:
    paths:
      - "data-jpa-post-service/**"
    branches:
      - master
  pull_request:
    paths:
      - "data-jpa-post-service/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Start up databases via Docker Compose 
        run: |
            docker-compose up -d postgres
            docker ps -a              
            
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        # with:
            # arguments: build
            # build-root-directory: post-service
      - name: Execute Gradle build
        run: |
          cd data-jpa-post-service
          chmod +x gradlew
          ./gradlew build
