# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: rxjava3-vertx-pg-client

on:
  push:
    paths:
      - "rxjava3-vertx-pg-client/**"
    branches:
      - master
  pull_request:
    paths:
      - "rxjava3-vertx-pg-client/**"
    types:
      - opened
      - synchronize
      - reopened
defaults:
 run:
  working-directory: ./rxjava3-vertx-pg-client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - name: Start up databases via Docker Compose 
        run: |
            docker compose up -d postgres
            docker ps -a              
            
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        # with:
          # arguments: build
          # build-root-directory: rxjava3-vertx-pg-client
      - name: Execute Gradle build
        run: |
          chmod +x gradlew
          ./gradlew build
